#!/bin/sh
#	Copyright (c) 1992 AT&T - All rights reserved.
PATH=/bin:/usr/bin
file=$1
case "$2" in
-f)	echo "$file"
	cat > $file
	;;
"")	echo "$file?"
	read yn < /dev/tty
	case "$yn" in
	[Yy]*)	cat > $file
	esac
esac
